### ISSUE TITLE
Examples do not compile on arduino uno

### ISSUE THREAD

**Issue by descampsa** [hideakitai/DRV2667#1]
Hi,

Thank you for sharing your code, but i can't get it to work on arduino uno.

The examples do not compile without modification.
I can compile the example_uno by replacing the SynthChunk struct by Synthesizer, removing the begin and replacing setSynthsizer by addSynthesizer, but i am not sure it is correct and it does not appear to work.

Could you provide a functionnal example?

**Comment by hideakitai** [comment]
@descampsa So sorry for the late reply... if you still want Uno to work, reopen and let me know!
