### ISSUE TITLE
Stops working after power cycle 

### ISSUE THREAD

**Issue by jmc1228** [hideakitai/DRV2667#2]
I am using this library with an I2C mux. In the simple code below, the motor buzzes every 3 seconds until I power cycle, at which point it stops working unless the code is reflashed. By the way, I am using a SAMD51J19a chip (like the one on the Adafruit Feather) and an Adafruit Feather M4 bootloader on custom board. 

```
#include <Wire.h>
#include "DRV2667.h"
#include <SparkFun_I2C_Mux_Arduino_Library.h>       
QWIICMUX myMux;
DRV2667 drv;

void setup()
{   

struct EmbeddedDevices::DRV2667::Synthesizer synth {
    {255, 0x17, 10, 0x12},
};

  
 Wire.begin();
 myMux.begin(); 

  if (myMux.begin() == false)
  {  
    while (1);
  }
 
  myMux.setPort(3); //Connect master to port labeled '1' on the mux
     drv.attatch(Wire);
     drv.addSynthesizer(synth); 
     drv.setWaveformOrderAndID(0,1); 
     drv.gain(DRV2667::Gain::D50V_A348dB);  
}

void loop()
{
        drv.play();
        delay(3000); //Wait for the wavkVkke to play;

}
```

**Comment by hideakitai** [comment]
Hi, sorry for the late reply. 
Is the example works as is? Modifying the example causes such behavior?

https://github.com/hideakitai/DRV2667/blob/master/examples/example/example.ino

**Comment by jmc1228** [comment]
I cannot test the pure example code because my board uses an I2C MUX, so I must add code to configure this MUX. But what I can tell you is that the Yurikleb library (https://github.com/yurikleb/DRV2667) does not show this power cycling issue on my board, so it is something related to the difference between these two libraries.

**Comment by hideakitai** [comment]
Sorry, this library is not maintained anymore. Please use https://github.com/yurikleb/DRV2667 instead.
