### ISSUE TITLE
Error while importing the library

### ISSUE THREAD

**Issue by dhairya02** [hideakitai/DRV2667#3]
Hi, 
I get the following error while importing the DRV2667 library from arduino.

In file included from C:\Users\abhis\OneDrive\Documents\Arduino\sketch_nov30a\sketch_nov30a.ino:1:0:
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h:123:39: error: 'SynthChunk' does not name a type
             void addSynthesizer(const SynthChunk* synthparams, const uint8_t size_of_synth)
                                       ^~~~~~~~~~
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h: In member function 'void EmbeddedDevices::DRV2667::DRV2667::addSynthesizer(const int*, uint8_t)':
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h:162:58: error: request for member 'amp' in '*(synthparams + ((sizetype)(((unsigned int)i) * 2)))', which is of non-class type 'const int'
                     write(start_addr + 0, synthparams[i].amp);
                                                          ^~~
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h:163:58: error: request for member 'freq' in '*(synthparams + ((sizetype)(((unsigned int)i) * 2)))', which is of non-class type 'const int'
                     write(start_addr + 1, synthparams[i].freq);
                                                          ^~~~
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h:164:58: error: request for member 'cycle' in '*(synthparams + ((sizetype)(((unsigned int)i) * 2)))', which is of non-class type 'const int'
                     write(start_addr + 2, synthparams[i].cycle);
                                                          ^~~~~
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h:165:58: error: request for member 'envelop' in '*(synthparams + ((sizetype)(((unsigned int)i) * 2)))', which is of non-class type 'const int'
                     write(start_addr + 3, synthparams[i].envelop);
                                                          ^~~~~~~
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h: At global scope:
C:\Users\abhis\OneDrive\Documents\Arduino\libraries\DRV2667/DRV2667.h:299:50: error: 'SynthChunk' in namespace 'EmbeddedDevices::DRV2667' does not name a type
 using DRV2667Effects = EmbeddedDevices::DRV2667::SynthChunk;
                                                  ^~~~~~~~~~
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

**Comment by hideakitai** [comment]
Sorry, this library is not maintained anymore. Please use https://github.com/yurikleb/DRV2667 instead.
